---------------------------------
[2024-01-08 23:03:20][INFO][200]:La conexion [dbconn_standard] esta desabilitada en el archivo .config
---------------------------------
[2024-01-08 23:03:20][INFO][200]:Iniciando ...
---------------------------------
[2024-01-08 23:03:20][INFO][200]:Se van a inferir 39 entidades
---------------------------------
[2024-01-08 23:10:18][EXCEPTION][500]:PYTHON-EXCEPTION:

>>>>>>>>>>>>>>>[TRACEBACK]<<<<<<<<<<<<<<<

  File "/home/alanromero/crowd-counting/src/inference/main.py", line 10, in <module>
    ProjectDirector.go( sys.argv )
  File "/home/alanromero/crowd-counting/src/inference/System/Director/ProjectDirector.py", line 141, in go
    ProjectDirector().setFlux( argv )
  File "/home/alanromero/crowd-counting/src/inference/System/Director/ProjectDirector.py", line 121, in setFlux
    asyncio.run(self.__play(
  File "/home/alanromero/anaconda3/envs/infer/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/alanromero/anaconda3/envs/infer/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/alanromero/crowd-counting/src/inference/System/Director/ProjectDirector.py", line 82, in __play
    person_entities = await infer.create_person_entities(camera_entities)
  File "/home/alanromero/crowd-counting/src/inference/System/App/InferProcedures/InferProcedures.py", line 59, in create_person_entities
    entities.append( await self.orion.infer(camera, decryptedF))
  File "/home/alanromero/crowd-counting/src/inference/System/App/OrionProcedures/OrionProcedures.py", line 105, in infer
    entities = self.track_video(filevideo, model, time)
  File "/home/alanromero/crowd-counting/src/inference/System/App/OrionProcedures/OrionProcedures.py", line 159, in track_video
    entities = {
  File "/home/alanromero/crowd-counting/src/inference/System/App/OrionProcedures/OrionProcedures.py", line 162, in <dictcomp>
    _class=max(v['classes'], key=v['classes'].count),

>>>>>>>>>>>>>>[ERROR_DESC]<<<<<<<<<<<<<<<

  [ValueError]:max() arg is an empty sequence

>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<

